name: Deploy Apache

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decrypt SSH key
        run: echo ${{ secrets.SSH_KEY }} | base64 -d > ~/.ssh/deploy_key && chmod 600 ~/.ssh/deploy_key

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y apache2

      - name: Copy Apache config
        run: scp -r -i ~/.ssh/deploy_key apache-config/* ubuntu@204.236.255.55:/etc/apache2/sites-available/

      - name: Enable site
        run: ssh -i ~/.ssh/deploy_key ubuntu@204.236.255.55 sudo a2ensite your-site.conf

      - name: Restart Apache
        run: ssh -i ~/.ssh/deploy_key ubuntu@204.236.255.55 sudo systemctl restart apache2
