name: Setup MySQL 8 and Java JDK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Commands to deploy your application (e.g., copy files, restart services, etc.)


    - name: Set up MySQL 8
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo mysql_secure_installation
        # Follow the prompts to secure MySQL installation

    - name: Set up Java JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build and test
      run: |
        # Your build and test commands go here

    env:
      DB_HOST: "34.201.220.59"
      DB_USER: "Test"
      DB_PASSWORD: "Test@!234"
